services:
  abu_engine:
    build: ./abu_engine
    container_name: abu_engine
    ports:
      - "8000:8000"
    restart: always

  lilly_engine:
    build: ./lilly_engine
    container_name: lilly_engine
    ports:
      - "8001:8001"
    restart: always
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - USE_ASSISTANTS=${USE_ASSISTANTS:-true}
      - ABU_URL=http://abu_engine:8000
      - OPENAI_ASSISTANT_ID=${OPENAI_ASSISTANT_ID}

  next_app:
    build: ./next_app
    container_name: next_app
    ports:
      - "3000:3000"
    restart: always
    environment:
      - NEXT_PUBLIC_ABU_URL=http://localhost:8000
      - NEXT_PUBLIC_LILLY_URL=http://localhost:8001
